#!/bin/sh

# script/publish: Build and upload to github pages

set -e

cd "$(dirname "$0")/.."

script/bootstrap

npm run build
npm run minify
mv build/main.min.js build/main.js

TEMPORARY_DIRECTORY=`mktemp -d`
cp -r build/. $TEMPORARY_DIRECTORY
cd $TEMPORARY_DIRECTORY

git init
git add .
git commit -m "Build commit"
git remote add origin git@github.com:sch/turnabout.git
git push origin HEAD:gh-pages --force
