#!/bin/sh

# script/test:        Run tests for this project
#
# script/test runner: Run tests for this project continuously

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [ "$1" == "runner" ]; then
  echo "==> Running tests when files change..."
  npm run test-runner
else
  echo "==> Running tests once:"
  npm test
fi
