#!/bin/sh

# script/test:        Run tests for this project
#
# script/test runner: Run tests for this project continuously

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [[ $1 == "runner" ]]; then
  npm run test-runner
else
  npm test
fi
